[build]
  # This is handled by GitHub Actions, but kept for reference
  publish = "combined-site"
  command = "echo 'Built by GitHub Actions'"

[build.environment]
  NODE_VERSION = "20"
  DOTNET_VERSION = "8.0"

# Redirect old /docs/blog/ URLs to root (where blog now lives)
[[redirects]]
  from = "/docs/blog/*"
  to = "/:splat"
  status = 301
  force = true

# Redirect old /posts/ URLs to root (where blog now lives)
[[redirects]]
  from = "/posts/*"
  to = "/:splat"
  status = 301
  force = true

# Redirect /docs/docs/ to /docs/
[[redirects]]
  from = "/docs/docs/*"
  to = "/docs/:splat"
  status = 301
  force = true

# Redirect /docs to root
[[redirects]]
  from = "/docs"
  to = "/"
  status = 301

# SPA routing for Docusaurus (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"