[build]
  # This is handled by GitHub Actions, but kept for reference
  publish = "combined-site"
  command = "echo 'Built by GitHub Actions'"

[build.environment]
  NODE_VERSION = "20"
  DOTNET_VERSION = "8.0"

# Redirect old /docs/ URLs to new root URLs
[[redirects]]
  from = "/docs/blog/*"
  to = "/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs/docs/*"
  to = "/docs/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs"
  to = "/"
  status = 301

# Redirect old Statiq URLs to new blog
[[redirects]]
  from = "/posts/*"
  to = "/posts/:splat"
  status = 200

# SPA routing for Docusaurus (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"