when:
  - event: push
    branch:
      - main
      - copilot/*
steps:
  - name: typecheck
    image: node:20
    commands:
      - cd src/docs
      - npm ci --silent
      - npm run typecheck
  
  - name: build
    image: debian
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
      - chmod +x executable

  - name: a-test-step
    image: golang:1.16
    commands:
      - echo "Testing ..."
      - ./executable
